common:
  app: amazing-app
  shortname: amazeapp
  team: example
  ingress:
    trafficType: public
  container:
    uid: 101
    image: nginxinc/nginx-unprivileged:stable-alpine
    probes:
      liveness:
        path: /
      readiness:
        path: /
