multi-1:
  app: amazing-app-multi
  shortname: amazemult
  team: example
  releaseName: amazing-app-multi
  ingress:
    trafficType: public
  container:
    uid: 101
    image: nginxinc/nginx-unprivileged:stable-alpine
    probes:
      liveness:
        path: /
      readiness:
        path: /

multi-2:
  app: amazing-app-multi-2
  shortname: amazemlt2
  team: example
  releaseName: amazing-app-multi-2
  ingress:
    enabled: false
  container:
    uid: 101
    image: nginxinc/nginx-unprivileged:stable-alpine
    probes:
      liveness:
        path: /
      readiness:
        path: /
