name: Entur/Helm/Deploy

on:
  workflow_call:
    inputs:
      image:
        description: "The image to deploy, on the form app:tag"
        required: true
        type: string
      environment:
        description: "The target environment"
        required: true
        type: string
      chart:
        description: "The chart, defaults to `helm/$repository_name`"
        type: string
        default: "repo_name"
      values:
        description: "The values file in `./helm/$app/env/`, default `$environment.yaml`"
        type: string
        default: "values"
      release_name:
        description: "The release name, defaults to repository name"
        type: string
        default: "repo_name"
      namespace:
        description: "The namespace to use, defaults to repository name"
        type: string
        default: "repo_name"
      cloud_provider:
        description: "Which repository to use. GCP/Azure"
        type: string
        default: "GCP"
      timeout_minutes:
        description: "Time out after x minutes"
        type: number
        default: 10
      project_id:
        type: string
        description: "Do not use this input"
      cluster_name:
        type: string
        description: "Do not use this input"
jobs:
  helm-deploy:
    name: Helm deploy
    environment: ${{ inputs.environment }}
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    timeout-minutes: ${{ inputs.timeout_minutes }}
    runs-on: ubuntu-latest
    steps:
      - id: set-env
        shell: bash
        run: |
          echo "GHA_HELM_DEPLOY_ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV
          echo "GHA_HELM_DEPLOY_IMAGE=${{ inputs.image }}" >> $GITHUB_ENV
          echo "GHA_HELM_DEPLOY_CLOUD_PROVIDER=${{ inputs.cloud_provider }}" >> $GITHUB_ENV
          echo "GHA_HELM_DEPLOY_RELEASE_NAME=${{ inputs.release_name }}" >> $GITHUB_ENV
          echo "GHA_HELM_DEPLOY_CHART=${{ inputs.chart }}" >> $GITHUB_ENV
          echo "GHA_HELM_DEPLOY_VALUES=${{ inputs.values }}" >> $GITHUB_ENV
          echo "GHA_HELM_DEPLOY_NAMESPACE=${{ inputs.namespace }}" >> $GITHUB_ENV
          echo "GHA_HELM_DEPLOY_REGISTRY=eu.gcr.io/entur-system-1287" >> $GITHUB_ENV
      - id: set-release-name
        if: env.GHA_HELM_DEPLOY_RELEASE_NAME == 'repo_name'
        shell: bash
        run: |
          echo "GHA_HELM_DEPLOY_RELEASE_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - id: set-chart-name
        if: env.GHA_HELM_DEPLOY_CHART == 'repo_name'
        shell: bash
        run: |
          echo "GHA_HELM_DEPLOY_CHART=helm/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - id: set-values-file
        if: env.GHA_HELM_DEPLOY_VALUES == 'values'
        shell: bash
        run: |
          echo "GHA_HELM_DEPLOY_VALUES=${{ inputs.environment }}.yaml" >> $GITHUB_ENV
      - id: set-namespace
        if: env.GHA_HELM_DEPLOY_NAMESPACE == 'repo_name'
        shell: bash
        run: |
          echo "GHA_HELM_DEPLOY_NAMESPACE=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - id: verify-cloud-provider
        if: env.GHA_HELM_DEPLOY_CLOUD_PROVIDER != 'GCP' && env.GHA_HELM_DEPLOY_CLOUD_PROVIDER != 'Azure'
        shell: bash
        run: |
          echo "cloud_provider can only be GCP or Azure"
          exit 1
      - id: set-registry-azure
        if: env.GHA_HELM_DEPLOY_CLOUD_PROVIDER == 'Azure'
        shell: bash
        run: |
          echo "GHA_HELM_DEPLOY_REGISTRY=acrentur001.azurecr.io/entur" >> $GITHUB_ENV
      - uses: actions/checkout@v4.1.2
      - id: install
        uses: azure/setup-helm@v4
      - uses: entur/gha-meta/.github/actions/cloud-auth@v1.1.1
        with:
          environment: ${{ env.GHA_HELM_DEPLOY_ENVIRONMENT }}
          cloud_provider: ${{ env.GHA_HELM_DEPLOY_CLOUD_PROVIDER }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}
          azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - uses: entur/gha-meta/.github/actions/k8s-auth@v1.1.1
        with:
          environment: ${{ env.GHA_HELM_DEPLOY_ENVIRONMENT }}
          cloud_provider: ${{ env.GHA_HELM_DEPLOY_CLOUD_PROVIDER }}
          project_id: ${{ inputs.project_id }}
          cluster_name: ${{ inputs.cluster_name }}
          azure_cluster_resource_group: ${{ vars.AZURE_CLUSTER_RESOURCE_GROUP }}
          azure_cluster_name: ${{ vars.AZURE_CLUSTER_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - id: deploy-given-tag
        name: Helm deploy ./${{ env.GHA_HELM_DEPLOY_CHART }}
        shell: bash
        run: |
          helm dependency update ./${{ env.GHA_HELM_DEPLOY_CHART }}
          helm upgrade ${{ env.GHA_HELM_DEPLOY_RELEASE_NAME }} ./${{ env.GHA_HELM_DEPLOY_CHART }}/ \
            -f ${{ env.GHA_HELM_DEPLOY_CHART }}/env/${{ env.GHA_HELM_DEPLOY_VALUES }} \
            --namespace ${{ env.GHA_HELM_DEPLOY_NAMESPACE }} \
            --set common.container.image=${{ env.GHA_HELM_DEPLOY_REGISTRY }}/${{ env.GHA_HELM_DEPLOY_IMAGE }} \
            --install \
            --atomic
