---
name: Entur/Helm/Deploy

on:
  workflow_call:
    inputs:
      image:
        description: "The image to deploy, on the form app:tag. Use `na` value to skip replacing the image version in the helm config."
        required: true
        type: string
      cloud_provider:
        description: "Which cloud service provider to use - Google Cloud: 'gcp' or Azure: 'az'"
        type: string
        default: "gcp"
      environment:
        type: string
        description: "GitHub environment to use Google Cloud: (dev, tst, prd) or Azure: (az-dev, az-test, az-prod)"
        required: true
      chart:
        description: "The chart, defaults to `helm/$repository_name`"
        type: string
        default: "repo_name"
      values:
        description: "The values file in `./helm/$app/env/`, default `$environment.yaml`"
        type: string
        default: "values"
      release_name:
        description: "The release name, defaults to repository name"
        type: string
        default: "repo_name"
      namespace:
        description: "The namespace to use, defaults to repository name"
        type: string
        default: "repo_name"
      gcp_project_id:
        type: string
        description: "Do not use this input"
      gcp_cluster_name:
        type: string
        description: "Do not use this input"
      gcp_cluster_location:
        type: string
        description: "Defaults to europe-west1"
        default: "europe-west1"
      timeout_minutes:
        description: "Job timeout in minutes. Helm deploy timeout is half of this value to enable rollback. Default is 30 minutes."
        type: number
        default: 30
      git_ref:
        description: "Git reference to check out before deployment. This can be used as an override if necessary"
        type: string
        required: false
    outputs:
      HELM_DEPLOY_STATUS:
        description: "Helm Deploy Status 0: Success, 1: Failed, 2: Rollback, 3: Rollback Failed"
        value: ${{ jobs.helm-deploy.outputs.HELM_DEPLOY_STATUS }}
jobs:
  helm-deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout_minutes }}
    name: Helm deploy
    environment: ${{ inputs.environment }}
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    env:
      GHA_HELM_DEPLOY_ENVIRONMENT: ${{ inputs.environment }}
      GHA_HELM_DEPLOY_IMAGE: ${{ inputs.image }}
      GHA_HELM_DEPLOY_CLOUD_PROVIDER: ${{ inputs.cloud_provider }}
      GHA_HELM_DEPLOY_RELEASE_NAME: ${{ inputs.release_name }}
      GHA_HELM_DEPLOY_CHART: ${{ inputs.chart }}
      GHA_HELM_DEPLOY_VALUES: ${{ inputs.values }}
      GHA_HELM_DEPLOY_NAMESPACE: ${{ inputs.namespace }}
      GHA_HELM_DEPLOY_ENV: ${{inputs.environment }}
      GHA_HELM_DEPLOY_REGISTRY: eu.gcr.io/entur-system-1287
      GHA_HELM_DEPLOY_GCP_PROJECT_ID: ${{ inputs.gcp_project_id }}
      GHA_HELM_DEPLOY_GCP_CLUSTER_NAME: ${{ inputs.gcp_cluster_name }}
      GHA_HELM_DEPLOY_GCP_CLUSTER_LOCATION: ${{ inputs.gcp_cluster_location }}
      GHA_GIT_REF: ${{ inputs.git_ref }}
      # ignore "context access might be invalid" warning
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ vars.SERVICE_ACCOUNT }}
      GCP_PROJECT_ID: ${{ inputs.project_id }}
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLUSTER_NAME: ${{ vars.AZURE_CLUSTER_NAME  }}
      AZURE_CLUSTER_RESOURCE_GROUP: ${{ vars.AZURE_CLUSTER_RESOURCE_GROUP }}
    outputs:
      HELM_DEPLOY_STATUS: ${{ steps.helm-deploy.outputs.HELM_DEPLOY_STATUS }}
    steps:
      - id: verify-cloud-provider
        if: env.GHA_HELM_DEPLOY_CLOUD_PROVIDER != 'gcp' && env.GHA_HELM_DEPLOY_CLOUD_PROVIDER != 'az'
        shell: bash
        run: |
          echo "Invalid cloud provider input: ${GHA_HELM_DEPLOY_CLOUD_PROVIDER}"
          echo "Valid options are: 'gcp' or 'az'"
          exit 1
      - id: set-release-name
        if: env.GHA_HELM_DEPLOY_RELEASE_NAME == 'repo_name'
        shell: bash
        run: |
          echo "GHA_HELM_DEPLOY_RELEASE_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - id: set-chart-name
        if: env.GHA_HELM_DEPLOY_CHART == 'repo_name'
        shell: bash
        run: |
          echo "GHA_HELM_DEPLOY_CHART=helm/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - id: set-namespace
        if: env.GHA_HELM_DEPLOY_NAMESPACE == 'repo_name'
        shell: bash
        run: |
          echo "GHA_HELM_DEPLOY_NAMESPACE=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - id: set-values-file
        if: env.GHA_HELM_DEPLOY_VALUES == 'values'
        shell: bash
        run: |
          echo "GHA_HELM_DEPLOY_VALUES=values-kub-ent-${GHA_HELM_DEPLOY_ENV}.yaml" >> $GITHUB_ENV
      - id: set-registry-azure
        if: env.GHA_HELM_DEPLOY_CLOUD_PROVIDER == 'az'
        shell: bash
        run: |
          echo "GHA_HELM_DEPLOY_REGISTRY=acrentur001.azurecr.io" >> $GITHUB_ENV
      - id: verify-clustername-az
        name: Verify Cluster Name Azure
        shell: bash
        if: inputs.cloud_provider == 'az' && !env.AZURE_CLUSTER_NAME
        run: |
          echo "GitHub repository environment variable AZURE_CLUSTER_NAME is not set. Setup using tf-azure-apps. Exiting."
          exit 1
      - id: checkout-default-ref
        uses: actions/checkout@v4.1.7
        if: env.GHA_GIT_REF == ''
      - id: checkout-specific-ref
        uses: actions/checkout@v4.1.7
        if: env.GHA_GIT_REF != ''
        with:
          ref: ${{ env.GHA_GIT_REF }}
      - id: install
        uses: azure/setup-helm@v4
      - uses: entur/gha-meta/.github/actions/cloud-auth@v1
        with:
          environment: ${{ env.GHA_HELM_DEPLOY_ENVIRONMENT }}
          cloud_provider: ${{ env.GHA_HELM_DEPLOY_CLOUD_PROVIDER }}
          gcp_workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          gcp_service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
          azure_client_id: ${{ env.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ env.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ env.AZURE_SUBSCRIPTION_ID }}
      - uses: entur/gha-meta/.github/actions/k8s-auth@v1
        with:
          environment: ${{ env.GHA_HELM_DEPLOY_ENVIRONMENT }}
          cloud_provider: ${{ env.GHA_HELM_DEPLOY_CLOUD_PROVIDER }}
          gcp_project_id: ${{ env.GHA_HELM_DEPLOY_GCP_PROJECT_ID }}
          gcp_cluster_name: ${{ env.GHA_HELM_DEPLOY_GCP_CLUSTER_NAME }}
          gcp_cluster_location: ${{ env.GHA_HELM_DEPLOY_GCP_CLUSTER_LOCATION }}
          azure_cluster_resource_group: ${{ env.AZURE_CLUSTER_RESOURCE_GROUP }}
          azure_cluster_name: ${{ env.AZURE_CLUSTER_NAME }}
          azure_token: ${{ secrets.GITHUB_TOKEN }}
      - id: helm-deploy
        name: Helm deploy ./${{ env.GHA_HELM_DEPLOY_CHART }}
        uses: entur/gha-helm/.github/actions/helm-deploy@v1
        with:
          timeout_minutes: ${{ inputs.timeout_minutes }}
          image: ${{ env.GHA_HELM_DEPLOY_IMAGE }}
          release_name: ${{ env.GHA_HELM_DEPLOY_RELEASE_NAME }}
          chart: ${{ env.GHA_HELM_DEPLOY_CHART }}
          values: ${{ env.GHA_HELM_DEPLOY_VALUES }}
          namespace: ${{ env.GHA_HELM_DEPLOY_NAMESPACE }}
