name: Entur/Helm/Lint

on:
  workflow_call:
    inputs:
      environment:
        description: "The target environment"
        required: true
        type: string
      chart:
        description: "The chart, defaults to `helm/$repository_name`"
        type: string
        default: "default"
      values:
        description: "The values file, default `$environment.yaml`. Must be in env/ subfolder from chart."
        type: string
        default: "default"
      timeout_minutes:
        description: "Job timeout in minutes"
        type: number
        default: 3

jobs:
  helm-lint:
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout_minutes }}
    name: Helm lint
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    env:
      GHA_HELM_LINT_CHART: ${{ inputs.chart }}
      GHA_HELM_LINT_VALUES: ${{ inputs.values }}
      GHA_HELM_LINT_ENV: ${{ inputs.environment }}
    steps:
      - id: set-chart-name
        shell: bash
        if: env.GHA_HELM_LINT_CHART == 'default'
        run: |
          echo "GHA_HELM_LINT_CHART=helm/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - id: set-values-file
        shell: bash
        if: env.GHA_HELM_LINT_VALUES == 'default'
        run: |
          echo "GHA_HELM_LINT_VALUES=values-kub-ent-${GHA_HELM_LINT_ENV}.yaml" >> $GITHUB_ENV
      - uses: actions/checkout@v4.1.6
      - id: install
        uses: azure/setup-helm@v4
      - id: lint
        shell: bash
        run: |
          helm lint \
            --quiet \
            "${GHA_HELM_LINT_CHART}" \
            -f "${GHA_HELM_LINT_CHART}/env/${GHA_HELM_LINT_VALUES}"
